# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80ca5f75d491ba8fbc7192aa4bec77c69c8d0fe9d1ee1669acec3492d926b9183c479b1adb8933dde1e84ded30477be34c0ff2f7aac06e8f0a4435905a52cfde

test:
  secret_key_base: 0e8f56f3eff2c144fe5a389a169843475a5ca80c9aca28559138b732e9d983938a59f2e2daeb87da0c687e2c83756378dc589d591cd35aab53f1e772fbb4d065

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
